# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-05-22 01:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0003_auto_20170522_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfoformmodel',
            name='in_papers',
            field=models.IntegerField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userinfoformmodel',
            name='in_patent',
            field=models.IntegerField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userinfoformmodel',
            name='na_papers',
            field=models.IntegerField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userinfoformmodel',
            name='na_patent',
            field=models.IntegerField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userinfoformmodel',
            name='ranking_in_major',
            field=models.CharField(choices=[(b'0', b'---\xe4\xb8\x93\xe4\xb8\x9a\xe6\x8e\x92\xe5\x90\x8d---'), (b'top 5%', b'top 5%'), (b'top 10%', b'top 10%'), (b'top 30%', b'top 30%'), (b'top 50%', b'top 50%')], default=b'0', max_length=20),
        ),
        migrations.AlterField(
            model_name='userinfoformmodel',
            name='score_GRE',
            field=models.IntegerField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userinfoformmodel',
            name='score_GRE_Anal',
            field=models.IntegerField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userinfoformmodel',
            name='score_GRE_Quan',
            field=models.IntegerField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userinfoformmodel',
            name='score_GRE_Verbal',
            field=models.IntegerField(blank=True, max_length=20, null=True),
        ),
    ]
