# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-05-22 05:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0005_userinfoformmodel_result_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfoformmodel',
            name='result_desc',
            field=models.CharField(max_length=40),
        ),
    ]
