# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-06-03 12:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0007_auto_20170603_1832'),
    ]

    operations = [
        migrations.RenameField(
            model_name='highschoolformmodel',
            old_name='cell_phone_number_1',
            new_name='cell_phone_number',
        ),
        migrations.RenameField(
            model_name='highschoolformmodel',
            old_name='first_name_1',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='highschoolformmodel',
            old_name='graduate_school_1',
            new_name='graduate_school',
        ),
        migrations.RenameField(
            model_name='highschoolformmodel',
            old_name='intention_country_1',
            new_name='intention_country',
        ),
        migrations.RenameField(
            model_name='highschoolformmodel',
            old_name='intention_school_1',
            new_name='intention_school',
        ),
        migrations.RenameField(
            model_name='highschoolformmodel',
            old_name='last_name_1',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='highschoolformmodel',
            old_name='recommendations_1',
            new_name='recommendations',
        ),
        migrations.RenameField(
            model_name='highschoolformmodel',
            old_name='research_1',
            new_name='research',
        ),
    ]
